language: d
sudo: false
dist: trusty

services:
  - mongodb
  - redis-server

addons:
  apt:
    packages:
    - libevent-dev
    - libssl-dev
    - pkg-config
    - zlib1g-dev

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.079.0
  - dmd-2.068.2
  - ldc-1.8.0
  - ldc-1.3.0
  - ldc-1.2.0
  - ldc-1.1.1
  - ldc-1.0.0
  - dmd-2.075.0
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - dmd-2.071.2
  - dmd-2.070.2
  - dmd-2.069.2

env:
  - VIBED_DRIVER=libevent BUILD_EXAMPLE=1 RUN_TEST=1
  - VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0

matrix:
  exclude:
    - d: ldc-1.2.0
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0
    - d: ldc-1.1.1
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0
    - d: ldc-1.0.0
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0
  allow_failures:
    - d: dmd-beta
    - d: dmd-2.072.2 # incompatible dub version
    - d: ldc-1.1.1 # buggy dub version
    - d: ldc-1.3.0
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0
    - d: dmd-2.068.2
      env: VIBED_DRIVER=libasync BUILD_EXAMPLE=0 RUN_TEST=0

before_install:
  - pyenv global system 3.6
  - pip3 install 'meson>=0.42,!=0.43,!=0.44'

install:
  - mkdir .ntmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  - unzip .ntmp/ninja-linux.zip -d .ntmp

before_script:
  - export PATH=$PATH:$PWD/.ntmp

script: ./travis-ci.sh
